name: CI Pipeline for Merge Requests

# Trigger the pipeline for Pull Requests (Merge Requests)
on:
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch (adjust to your default branch)

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        # Pas besoin de preciser la version(Set Up) de NodeJs car il y a déjà dans GitHub

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run linting
        run: npm run lint
        working-directory: ./frontend

      - name: Build the frontend app
        run: npm run build
        working-directory: ./frontend

  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        # Pas besoin de preciser la version(Set Up) de dotnet car il y a déjà dans GitHub
      - name: Publish the backend app # Restore => Build => Publish
        run: dotnet publish --configuration Release --output ./backend/publish
        working-directory: ./backend
