name: CI Release Pipeline
#
# The Frontend job will build the React app and create a deployable artifact (e.g., a zip or tar file).
# The Backend job will publish the .NET app and create a deployable artifact.
# The artifacts for both frontend and backend will be stored in the GitHub Actions workflow and uploaded to be consumed by the CD pipeline.

on:
  #push:
  # tags:
  #    - 'v[0-9].[0-9].[0-9]'  # Trigger when a version tag is pushed, e.g., v1.0.0
  workflow_dispatch:  # Allow manual triggers

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    outputs:
      frontend_artifact: ${{ steps.upload_frontend.outputs.artifact_path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run linting
        run: npm run lint
        working-directory: ./frontend

      - name: Build the frontend app
        run: npm run build
        working-directory: ./frontend

      - name: Upload frontend artifact
        id: upload_frontend
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: ./frontend/dist

  build_backend:
    runs-on: ubuntu-latest
    outputs:
      backend_artifact: ${{ steps.upload_backend.outputs.artifact_path }}
    steps: # Ce sont juste des lignes de commandes dans la machine virtuelle en utilisant run pour ligne de commande et uses pour les actions (commande déjà developpée)
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish the app
        run: dotnet publish -c Release --property:PublishDir=publish # Publish the app to the publish folder of the API project
        working-directory: ./backend # specify where to find the sln file
  
      - name: Archive the artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: ./backend/ParkNDeploy.Api/publish
          retention-days: 5 # default is 90 days, quite a bit long